version: '2'
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ssldeadline
    ports:
      - "3306:3306"
    #volumes:
    #  - "$PWD/docker-init:/docker-entrypoint-initdb.d:ro"
